.class public Lcom/facebook/litho/config/ComponentsConfiguration;
.super Ljava/lang/Object;
.source "BL"


# static fields
.field public static final CAN_CHECK_GLOBAL_ANIMATOR_SETTINGS:Z

.field public static DEFAULT_BACKGROUND_THREAD_PRIORITY:I = 0x0

.field public static final DEFAULT_CHANGE_SET_THREAD_PRIORITY:I = 0x0

.field public static final IS_INTERNAL_BUILD:Z = false

.field public static final NEEDS_THEME_SYNCHRONIZATION:Z

.field public static final USE_INCREMENTAL_MOUNT_HELPER:Z = true

.field public static boostPerfLayoutStateFuture:Z

.field public static canInterruptAndMoveLayoutsBetweenThreads:Z

.field public static checkNeedsRemeasure:Z

.field public static debugHighlightInteractiveBounds:Z

.field public static debugHighlightMountBounds:Z

.field public static delegateToRenderCoreMount:Z

.field public static disableComponentHostPool:Z

.field public static disableGetAnnotationUsage:Z

.field public static disablePoolsEnd:Ljava/lang/String;

.field public static disablePoolsStart:Ljava/lang/String;

.field public static disableTransitionsExtensionForMountDelegate:Z

.field public static enableErrorBoundaryComponent:Z

.field public static enableLithoViewDebugOverlay:Z

.field public static enableOnErrorHandling:Z

.field public static enableRenderInfoDebugging:Z

.field public static enableShouldCreateLayoutWithNewSizeSpec:Z

.field public static enableThreadTracingStacktrace:Z

.field public static forceEnableTransitionsForInstrumentationTests:Z

.field public static ignoreStateUpdatesForScreenshotTest:Z

.field public static incrementalVisibilityHandling:Z

.field public static inheritPriorityFromUiThread:Z

.field public static isAnimationDisabled:Z

.field public static isDebugHierarchyEnabled:Z

.field public static isDebugModeEnabled:Z

.field public static isEndToEndTestRun:Z

.field public static isGlobalComponentsPoolEnabled:Z

.field public static isHooksImplEnabled:Z

.field public static isIncrementalMountGloballyDisabled:Z

.field public static isLayoutDiffingEnabled:Z

.field public static isPoolBisectEnabled:Z

.field public static isReconciliationEnabled:Z

.field public static onlyProcessAutogeneratedTransitionIdsWhenNecessary:Z

.field public static perfBoosterFactory:Lcom/facebook/litho/perfboost/LithoPerfBoosterFactory;
    .annotation build Landroidx/annotation/Nullable;
    .end annotation
.end field

.field public static prioritizeRenderingOnParallel:Z

.field public static shouldDisableDrawableOutputs:Z

.field public static shouldForceAsyncStateUpdate:Z

.field public static shouldForceComponentUpdateOnOrientationChange:Z

.field public static shouldUseDeepCloneDuringReconciliation:Z

.field public static skipVisChecksForFullyVisible:Z

.field public static threadPoolConfiguration:Lcom/facebook/litho/config/LayoutThreadPoolConfiguration;
    .annotation build Landroidx/annotation/Nullable;
    .end annotation
.end field

.field public static threadPoolForBackgroundThreadsConfig:Lcom/facebook/litho/config/LayoutThreadPoolConfiguration;
    .annotation build Landroidx/annotation/Nullable;
    .end annotation
.end field

.field public static unmountAllWhenComponentTreeSetToNull:Z

.field public static useCancelableLayoutFutures:Z

.field public static useExtensionsWithMountDelegate:Z

.field public static useGlobalKeys:Z

.field public static useIncrementalMountExtension:Z

.field public static useInternalNodesForLayoutDiffing:Z

.field public static useNewGenerateMechanismForGlobalKeys:Z

.field public static useSharedFutureOnParallel:Z

.field public static useTransitionsExtension:Z

.field public static useVisibilityExtension:Z


# direct methods
.method static constructor <clinit>()V
    .locals 4

    .line 1
    sget v0, Landroid/os/Build$VERSION;->SDK_INT:I

    .line 2
    .line 3
    const/4 v1, 0x1

    .line 4
    sput-boolean v1, Lcom/facebook/litho/config/ComponentsConfiguration;->CAN_CHECK_GLOBAL_ANIMATOR_SETTINGS:Z

    .line 5
    .line 6
    const/16 v2, 0x16

    .line 7
    .line 8
    const/4 v3, 0x0

    .line 9
    if-gt v0, v2, :cond_0

    .line 10
    .line 11
    const/4 v0, 0x1

    .line 12
    goto :goto_0

    .line 13
    :cond_0
    const/4 v0, 0x0

    .line 14
    :goto_0
    sput-boolean v0, Lcom/facebook/litho/config/ComponentsConfiguration;->NEEDS_THEME_SYNCHRONIZATION:Z

    .line 15
    .line 16
    const/4 v0, 0x5

    .line 17
    sput v0, Lcom/facebook/litho/config/ComponentsConfiguration;->DEFAULT_BACKGROUND_THREAD_PRIORITY:I

    .line 18
    .line 19
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->isDebugModeEnabled:Z

    .line 20
    .line 21
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->isDebugHierarchyEnabled:Z

    .line 22
    .line 23
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->debugHighlightInteractiveBounds:Z

    .line 24
    .line 25
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->enableLithoViewDebugOverlay:Z

    .line 26
    .line 27
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->debugHighlightMountBounds:Z

    .line 28
    .line 29
    const-string v0, "IS_TESTING"

    .line 30
    .line 31
    invoke-static {v0}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    .line 32
    .line 33
    .line 34
    move-result-object v0

    .line 35
    if-eqz v0, :cond_1

    .line 36
    .line 37
    const/4 v0, 0x1

    .line 38
    goto :goto_1

    .line 39
    :cond_1
    const/4 v0, 0x0

    .line 40
    :goto_1
    sput-boolean v0, Lcom/facebook/litho/config/ComponentsConfiguration;->isEndToEndTestRun:Z

    .line 41
    .line 42
    const-string v0, "litho.animation.disabled"

    .line 43
    .line 44
    invoke-static {v0}, Ljava/lang/System;->getProperty(Ljava/lang/String;)Ljava/lang/String;

    .line 45
    .line 46
    .line 47
    move-result-object v0

    .line 48
    const-string v2, "true"

    .line 49
    .line 50
    invoke-virtual {v2, v0}, Ljava/lang/String;->equals(Ljava/lang/Object;)Z

    .line 51
    .line 52
    .line 53
    move-result v0

    .line 54
    sput-boolean v0, Lcom/facebook/litho/config/ComponentsConfiguration;->isAnimationDisabled:Z

    .line 55
    .line 56
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->forceEnableTransitionsForInstrumentationTests:Z

    .line 57
    .line 58
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->enableOnErrorHandling:Z

    .line 59
    .line 60
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->enableErrorBoundaryComponent:Z

    .line 61
    .line 62
    sput-boolean v1, Lcom/facebook/litho/config/ComponentsConfiguration;->useGlobalKeys:Z

    .line 63
    .line 64
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->useNewGenerateMechanismForGlobalKeys:Z

    .line 65
    .line 66
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->unmountAllWhenComponentTreeSetToNull:Z

    .line 67
    .line 68
    const/4 v0, 0x0

    .line 69
    sput-object v0, Lcom/facebook/litho/config/ComponentsConfiguration;->threadPoolForBackgroundThreadsConfig:Lcom/facebook/litho/config/LayoutThreadPoolConfiguration;

    .line 70
    .line 71
    sput-object v0, Lcom/facebook/litho/config/ComponentsConfiguration;->threadPoolConfiguration:Lcom/facebook/litho/config/LayoutThreadPoolConfiguration;

    .line 72
    .line 73
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->enableThreadTracingStacktrace:Z

    .line 74
    .line 75
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->inheritPriorityFromUiThread:Z

    .line 76
    .line 77
    sput-boolean v1, Lcom/facebook/litho/config/ComponentsConfiguration;->enableShouldCreateLayoutWithNewSizeSpec:Z

    .line 78
    .line 79
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->onlyProcessAutogeneratedTransitionIdsWhenNecessary:Z

    .line 80
    .line 81
    sput-boolean v1, Lcom/facebook/litho/config/ComponentsConfiguration;->isReconciliationEnabled:Z

    .line 82
    .line 83
    sput-boolean v1, Lcom/facebook/litho/config/ComponentsConfiguration;->isLayoutDiffingEnabled:Z

    .line 84
    .line 85
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->enableRenderInfoDebugging:Z

    .line 86
    .line 87
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->canInterruptAndMoveLayoutsBetweenThreads:Z

    .line 88
    .line 89
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->isPoolBisectEnabled:Z

    .line 90
    .line 91
    const-string v2, "aaaaa"

    .line 92
    .line 93
    sput-object v2, Lcom/facebook/litho/config/ComponentsConfiguration;->disablePoolsStart:Ljava/lang/String;

    .line 94
    .line 95
    const-string v2, "zzzzz"

    .line 96
    .line 97
    sput-object v2, Lcom/facebook/litho/config/ComponentsConfiguration;->disablePoolsEnd:Ljava/lang/String;

    .line 98
    .line 99
    sput-boolean v1, Lcom/facebook/litho/config/ComponentsConfiguration;->prioritizeRenderingOnParallel:Z

    .line 100
    .line 101
    sput-boolean v1, Lcom/facebook/litho/config/ComponentsConfiguration;->useSharedFutureOnParallel:Z

    .line 102
    .line 103
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->checkNeedsRemeasure:Z

    .line 104
    .line 105
    sput-boolean v1, Lcom/facebook/litho/config/ComponentsConfiguration;->disableComponentHostPool:Z

    .line 106
    .line 107
    sput-object v0, Lcom/facebook/litho/config/ComponentsConfiguration;->perfBoosterFactory:Lcom/facebook/litho/perfboost/LithoPerfBoosterFactory;

    .line 108
    .line 109
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->shouldUseDeepCloneDuringReconciliation:Z

    .line 110
    .line 111
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->useInternalNodesForLayoutDiffing:Z

    .line 112
    .line 113
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->incrementalVisibilityHandling:Z

    .line 114
    .line 115
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->shouldForceAsyncStateUpdate:Z

    .line 116
    .line 117
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->useExtensionsWithMountDelegate:Z

    .line 118
    .line 119
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->delegateToRenderCoreMount:Z

    .line 120
    .line 121
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->disableTransitionsExtensionForMountDelegate:Z

    .line 122
    .line 123
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->shouldDisableDrawableOutputs:Z

    .line 124
    .line 125
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->useIncrementalMountExtension:Z

    .line 126
    .line 127
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->useVisibilityExtension:Z

    .line 128
    .line 129
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->useTransitionsExtension:Z

    .line 130
    .line 131
    sput-boolean v1, Lcom/facebook/litho/config/ComponentsConfiguration;->shouldForceComponentUpdateOnOrientationChange:Z

    .line 132
    .line 133
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->isGlobalComponentsPoolEnabled:Z

    .line 134
    .line 135
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->isHooksImplEnabled:Z

    .line 136
    .line 137
    sput-boolean v3, Lcom/facebook/litho/config/ComponentsConfiguration;->isIncrementalMountGloballyDisabled:Z

    .line 138
    .line 139
    return-void
.end method

.method public constructor <init>()V
    .locals 0

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method

.method public static isRenderInfoDebuggingEnabled()Z
    .locals 1

    .line 1
    sget-boolean v0, Lcom/facebook/litho/config/ComponentsConfiguration;->isDebugModeEnabled:Z

    .line 2
    .line 3
    if-eqz v0, :cond_0

    .line 4
    .line 5
    sget-boolean v0, Lcom/facebook/litho/config/ComponentsConfiguration;->enableRenderInfoDebugging:Z

    .line 6
    .line 7
    if-eqz v0, :cond_0

    .line 8
    .line 9
    const/4 v0, 0x1

    .line 10
    goto :goto_0

    .line 11
    :cond_0
    const/4 v0, 0x0

    .line 12
    :goto_0
    return v0
.end method
